make new option templateStyleguideAdditionalStylesheets optional...
denkwerk/npm-dw-styleguide pull request #13
Opened 2018-09-07 15:36 UTC by Jessman5

2018-09-07 15:54 UTC, Jessman5 commented
the second commit fixed it. @mariusbuescher

2018-09-10 07:03 UTC, Jessman5 commented
I also re-added a much needed body class that was (accidentally?) removed.

2018-09-10 07:28 UTC, mariusbuescher requested changes

2018-09-10 07:28 UTC, mariusbuescher commented on generate/setup.js
> +    } else {
Not needed here. By default the variable is already an array.

2018-09-10 07:31 UTC, Jessman5 commented
done.

2018-09-10 07:32 UTC, mariusbuescher approved these changes

2018-09-10 07:32 UTC, mariusbuescher commented
Nice, thank you.

2018-09-10 07:32 UTC, merged